### ISSUE TITLE
[windows] FlutterAppRequiredException: The current directory does not appear to be a Flutter application project.

### ISSUE THREAD

**Issue by ezet** [invertase/flutterfire_cli#12]
I am having issues running the tool on Windows. Same error with powershell, cmd and mingw. Firebase CLI is installed and configured for the project.

```
 flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.19043.1237], locale en-US)
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (14 hours ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code, 64-bit edition (version 1.31.1)
[√] Connected device (2 available)
```

```
Building package executables...
Built flutterfire_cli:flutterfire.
Installed executable flutterfire.
Activated flutterfire_cli 0.1.1+1.
PS .\flutter-app> flutterfire configure
FlutterAppRequiredException: The current directory does not appear to be a Flutter application project.
```

**Comment by smiskiv-hoopit** [comment]
Same for me on Mac OS

**Comment by Salakar** [comment]
Hey @ezet - any chance you could share the pubspec.yaml for current directory that you're running the CLI in?

**Comment by kirkcharlesniv** [comment]
Hello, I am currently experiencing this issue. This is my `pubspec.yaml` if this could help moving forward with this issue.

```
name: XXXXXXXX
description: XXXXXXXXX
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  flutter:
    sdk: flutter
  firebase_core: ^1.10.5
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  sentry_flutter: ^6.1.2
  percent_indicator: ^3.4.0

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
```
