### ISSUE TITLE
[bug]:  flutterfire configure Unhandled exception: type 'Null' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by Ziron-hub** [invertase/flutterfire_cli#171]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

0.2.7

### Firebase Tools version

11.25.2

### Flutter Doctor Output

flutter doctor -v
[✓] Flutter (Channel stable, 3.7.8, on Ubuntu 20.04.6 LTS 5.15.0-69-generic,
    locale pt_BR.UTF-8)
    • Flutter version 3.7.8 on channel stable at
      /home/aquila020/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (12 days ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/aquila020/Library/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_SDK_ROOT = /home/aquila020/Library/Android/Sdk
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /home/aquila020/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] Android Studio (version 2021.3)
    • Android Studio at /snap/android-studio/125/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.6 LTS
      5.15.0-69-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.146

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

### Description

I'm trying to use firestore from firebase and for that I need to configure firebase in my flutter project, but when I get to the step of using the command "flutterfire configure" it gives this error.

### Steps to reproduce

1. Install CLI of firebase
2. Use this command: "firebase login" and log in your firebase account
3. Install flutterfire: "dart pub global activate flutterfire_cli"
4. And run this: "flutterfire configure"

### Expected behavior

I hope this creates a firebase config file.

### Screenshots

![Captura de tela de 2023-04-02 19-08-12](https://user-images.githubusercontent.com/72367387/229381584-bed9ab7e-d39e-4325-b78e-da05393e22f3.png)

**Comment by kwek20** [comment]
Also mentioned here. I have the same issue
https://github.com/firebase/flutterfire/issues/7915

**Comment by krille-chan** [comment]
Hello, I'm the maintainer of FluffyChat and have the same problem. The content of the pubspec.yaml file I have tried this with is:

```yaml
name: fluffychat
description: Chat with your friends.
publish_to: none
# On version bump also increase the build number for F-Droid
version: 1.16.0+3523

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  adaptive_dialog: ^2.0.0
  animations: ^2.0.8
  archive: ^3.4.9
  async: ^2.11.0
  badges: ^3.1.2
  blurhash_dart: ^1.2.1
  callkeep: ^0.3.2
  chewie: ^1.7.1
  collection: ^1.17.2
  cupertino_icons: any
  desktop_drop: ^0.4.4
  desktop_notifications: ^0.6.3
  device_info_plus: ^9.1.0
  dynamic_color: ^1.6.8
  emoji_picker_flutter: ^1.6.3
  emoji_proposal: ^0.0.1
  emojis: ^0.9.9
  file_picker: ^6.1.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_blurhash: ^0.8.2
  flutter_cache_manager: ^3.3.0
  flutter_foreground_task: ^6.0.0+1
  flutter_highlighter: ^0.1.1
  flutter_html: ^3.0.0-beta.2
  flutter_html_table: ^3.0.0-beta.2
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^16.1.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^4.0.0
  flutter_math_fork: ^0.7.2
  flutter_olm: 1.3.2 # Keep in sync with scripts/prepare-web.sh ! 1.4.0 does currently not build on Android
  flutter_openssl_crypto: ^0.3.0
  flutter_ringtone_player: ^4.0.0+2
  flutter_secure_storage: ^9.0.0
  flutter_typeahead: ^4.8.0
  flutter_web_auth_2: ^3.0.4
  flutter_webrtc: ^0.9.46
  future_loading_dialog: ^0.3.0
  geolocator: ^7.6.2
  go_router: ^12.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.6
  image_picker: ^1.0.0
  intl: any
  just_audio: ^0.9.30
  keyboard_shortcuts: ^0.1.4
  latlong2: ^0.8.1
  linkify: ^5.0.0
  matrix: ^0.25.0
  matrix_homeserver_recommendations: ^0.3.0
  native_imaging: ^0.1.0
  package_info_plus: ^4.0.0
  pasteboard: ^0.2.0
  path_provider: ^2.0.9
  permission_handler: ^11.0.1
  provider: ^6.0.2
  punycode: ^1.0.0
  qr_code_scanner: ^1.0.0
  qr_flutter: ^4.0.0
  receive_sharing_intent: ^1.4.5
  record: 4.4.4 # Upgrade to 5 currently breaks playing on iOS
  scroll_to_index: ^3.0.1
  share_plus: ^7.2.1
  shared_preferences: ^2.2.0 # Pinned because https://github.com/flutter/flutter/issues/118401
  slugify: ^2.0.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+4
  sqflite_sqlcipher: ^2.2.1
  swipe_to_action: ^0.2.0
  tor_detector_web: ^1.1.0
  uni_links: ^0.5.1
  unifiedpush: ^5.0.1
  universal_html: ^2.2.4
  url_launcher: ^6.2.1
  vibration: ^1.8.3
  video_compress: ^3.1.1
  video_player: ^2.8.1
  wakelock_plus: ^1.1.3
  webrtc_interface: ^1.0.13

dev_dependencies:
  dart_code_metrics: ^5.7.5
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.0.3+1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  integration_test:
    sdk: flutter
  msix: ^3.6.2
  translations_cleaner: ^0.0.5

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: "assets/info-logo.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/
    - assets/js/
    - assets/js/package/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: RobotoMono
      fonts:
        - asset: fonts/Roboto/RobotoMono-Regular.ttf
    - family: NotoEmoji
      fonts:
        - asset: fonts/NotoEmoji/NotoColorEmoji.ttf

msix_config:
  display_name: FluffyChat
  publisher_display_name: FluffyChat
  publisher: CN=FluffyChat, O=Head of bad integration tests, L=Matrix, S=Internet, C=EU
  identity_name: chat.fluffy.fluffychat
  logo_path: assets\logo.png
  capabilities: internetClient, location, microphone, webcam
  protocol_activation: https
  app_uri_handler_hosts: fluffychat.im, matrix.to
  execution_alias: fluffychat
  sign_msix: false
  install_certificate: false

dependency_overrides:
  # Until https://github.com/mogol/flutter_secure_storage/issues/616 is fixed
  flutter_secure_storage_linux: 1.1.3
  geolocator_android:
    hosted:
      name: geolocator_android
      url: https://hanntech-gmbh.gitlab.io/free2pass/flutter-geolocator-floss
  # waiting for null safety
  # Upstream pull request: https://github.com/AntoineMarcel/keyboard_shortcuts/pull/13
  keyboard_shortcuts:
    git:
      url: https://github.com/TheOneWithTheBraid/keyboard_shortcuts.git
      ref: null-safety
  # blocked upgrade of package_info_plus for null safety
  # https://github.com/creativecreatorormaybenot/wakelock/pull/203
  wakelock_windows:
    git:
      url: https://github.com/chandrabezzo/wakelock.git
      ref: main
      path: wakelock_windows/

```
