### ISSUE TITLE
FlutterAppRequiredException: The current directory does not appear to be a Flutter application project.

### ISSUE THREAD

**Issue by fannar** [invertase/flutterfire_cli#45]
This error occurs when `pubspec.yml` has

```yaml
dependencies:
  flutter_localizations:
    sdk: flutter
```

instead of

```yaml
dependencies:
  flutter:
    sdk: flutter
```

If using localizations your `pubspec.yml`should be

```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
```

Some projects only have the `flutter_localizations` key and are missing the `flutter` key and therefore `flutterfire client` doesn't recognize the project as a Flutter project.

**Comment by fannar** [comment]
Flutter docs specify that `pubspec.yml` with Flutter localizations should be

```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
```

but some projects only have the `flutter_localizations` key.

**Comment by dancamdev** [comment]
I'm using the flutterfire configure along with localizations no problem.

is your pubspec file extension `.yml`? - might be worth to try changing that to `.yaml` - just a guess though.

**Comment by fannar** [comment]
This isn't a problem for me. Just reporting that if the `pubspec.yml` is missing 

```dart
dependencies:
  flutter:
    sdk: flutter
```

`flutterfire configure` doesn't work.

**Comment by cedvdb** [comment]
@Salakar Please reopen.

Here is our scenario:

The application itself is acting as a shell for other features. Flutter is part of our infrastructure. eg:

```yaml
dependencies:
  infrastructure:
    path: ../infrastructure/infrastructure
  payment:
    path: ../features/payment
```

Yes flutter is not a direct dependency, it is exported and some things are hidden from flutter itself 

There will be linting issues of course if that's allowed because the import won't import a direct dependency. So I suggest adding an optional header like l10n.yaml does, which is what we use it for, when a generator is involved:

```yaml
header: "// ignore_for_file: depend_on_referenced_packages"
```
