### ISSUE TITLE
FlutterAppRequiredException: The current directory does not appear to be a Flutter application project.

### ISSUE THREAD

**Issue by sezer** [invertase/flutterfire_cli#56]
When I try to `flutterfire configure` I got this error on  a windows machine. I'm able to run/debug and build my app.
I've create another empty project and it worked as expected. But for my current setup it is not working.

```
FlutterAppRequiredException: The current directory does not appear to be a Flutter application project.
```

`flutter doctor -v`

```
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version
    10.0.19043.1620], locale tr-TR)
    • Flutter version 2.10.3 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (6 weeks ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at C:\Users\sezer\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 33.0.0-rc1
    • ANDROID_HOME = C:\Users\sezer\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30711.63
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.66.1)
    • VS Code at C:\Users\sezer\AppData\Local\Programs\Microsoft VS Code

[√] Connected device (4 available)
    • ONEPLUS A3010 (mobile) • 127.0.0.1:60380 • android-x64    • Android 7.1.1 (API 25)
    • Windows (desktop)      • windows         • windows-x64    • Microsoft Windows [Version 10.0.19043.1620]
    • Chrome (web)           • chrome          • web-javascript • Google Chrome 100.0.4896.75
    • Edge (web)             • edge            • web-javascript • Microsoft Edge 99.0.1150.39

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

`pubspec.yaml`

```
name: sezer
description: sezer mobile app
publish_to: "none"
version: 1.0.0+4

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.14.0
  local_auth: ^1.1.11
  flutter_secure_storage: ^5.0.2
  cupertino_icons: ^1.0.2
  platform_device_id: ^1.0.1
  device_info_plus: ^3.2.2
  location: ^4.3.0
  url_launcher: ^6.0.20
  flutter_riverpod: ^1.0.3
  mobile_scanner: ^0.2.0
  font_awesome_flutter: ^10.1.0
  freezed_annotation: ^1.1.0
  dio: ^4.0.4
  lottie: ^1.2.2
  carousel_slider: ^4.0.0
  html: ^0.15.0
  flutter_native_splash: ^2.1.1
  video_player: ^2.3.0
  flutter_screenutil: ^5.3.1
  secure_application: ^3.8.0
  plaid_flutter: ^2.2.1
  badges: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
  freezed: ^1.1.1
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/fonts/
  fonts:
    - family: Gentona Book
      fonts:
        - asset: assets/fonts/Gentona-Book.otf
        - asset: assets/fonts/Gentona-Book-Bold.otf
          weight: 700
        - asset: assets/fonts/Gentona-Book-Italic.otf
          style: italic
  plugin:
    platforms:
      ios:
        pluginClass: AppDelegate

```

`flutterfire -v` 0.1.3

**Comment by myronsp** [comment]
I am also getting this same error, but on a Mac machine.

flutter doctor

`[✓] Flutter (Channel stable, 2.10.4, on macOS 11.6.4 20G417 darwin-x64, locale en-US)
    • Flutter version 2.10.4 at /Users/xxxxxDeveloper/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/xxxxx/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/myronswift/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (2 available)
    • iPhone 13 Pro Max (mobile) • 39DA6C59-BF17-4D75-A4A8-E164511D694C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available
`

pubspec.yaml

`name: xxxx
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+11
  google_maps_flutter: ^2.1.3
  firebase_auth: ^3.3.11
  firebase_analytics: ^9.1.2
  firebase_core: ^1.13.1
  geolocator: ^8.2.0
  equatable: ^2.0.3
  http: ^0.13.4
  flutter_rating_bar: ^4.0.0
  bloc: ^8.0.3
  provider: ^6.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
  
  assets:
     - images/
  fonts:
     - family: WorkSans
       fonts:
         - asset: fonts/WorkSans-Regular.ttf
         - asset: fonts/WorkSans-Black.ttf
`

flutterfire -v 0.2.0

**Comment by Salakar** [comment]
@sezer is there any reason your pubspec contains this:

```
  plugin:
    platforms:
      ios:
        pluginClass: AppDelegate
```

This is causing it currently to be detected as a flutter plugin rather than a flutter app
